---
application:
  name: "py"
  project: "check"
  publicly_accessible: true
routers:
- name: "main-py-roott"
  custom_domains:
  - branch: main
    domain: bojha.com.np
  routes:
  - application_name: "py"
    paths:
    - /
