---
application:
  name: "py"
  project: "check"
  publicly_accessible: true
  organization: "QoveryCommunity"
routers:
- name: "main-py-roott"
  custom_domains:
  - branch: main
    domain: bojha.com.np
  routes:
  - application_name: "py"
    paths:
    - /
- name: "main-py"
  custom_domains:
  - branch: main
    domain: www.bojha.com.np
  routes:
  - application_name: "py"
    paths:
    - /
