---
application:
  name: "py"
  project: "check"
  organization: "QoveryCommunity"
routers:
- name: "main-py"
  custom_domains:
  - branch: main
    domain: bojha.com.np
  routes:
  - application_name: "py"
    paths:
    - "/*"
